export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";


export const QUESTION_EDIT_REQUEST = 'QUESTION_EDIT_REQUEST';
export const QUESTION_EDIT_SUCCESS = 'QUESTION_EDIT_SUCCESS';
export const QUESTION_EDIT_FAIL = 'QUESTION_EDIT_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";
