export const CREATE_SUBTOPIC_REQUEST = "CREATE_SUBTOPIC_REQUEST";
export const CREATE_SUBTOPIC_SUCCESS = "CREATE_SUBTOPIC_SUCCESS";
export const CREATE_SUBTOPIC_FAIL = "CREATE_SUBTOPIC_FAIL";

export const GET_SUBTOPICS_REQUEST = "GET_SUBTOPICS_REQUEST";
export const GET_SUBTOPICS_SUCCESS = "GET_SUBTOPICS_SUCCESS";
export const GET_SUBTOPICS_FAIL = "GET_SUBTOPICS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";